### ISSUE TITLE
Is the old buildtogether.tech still available?

### ISSUE THREAD

**Issue by ThorodanBrom** [gvwilson/buildtogether.tech#1]
Hello @gvwilson,

I personally found `buildtogether.tech` to be an invaluable resource; something that I went back to from time to time and also shared with friends and colleagues. I noticed that the URL doesn't work anymore and the old repository/content and the repo history is quite young. I wanted to know if the material is being rewritten or has been taken down for any reason.

Regardless, many thanks for developing it, it really was a great book.

**Comment by gvwilson** [comment]
Hi @ThorodanBrom - I hope to rewrite it and repost it some day, but I was increasingly unhappy with both content and format, so I took it down pending time to fix it. In brief, I felt many parts repeated material that was already out there (e.g., on version control), while others were just hand-waving or hectoring (e.g., the material on inclusivity), and there wasn't nearly enough on evidence-based findings in software engineering research (see https://neverworkintheory.org/ - which, by the way, has another round of lightning talks in April). If you'd like to be notified if and when it goes back up, please mail me (gvwilson@third-bit.com) and I'll mail you when the time comes. Cheers - Greg
