### ISSUE TITLE
Mismatched columns in table of contents

### ISSUE THREAD

**Issue by czeildi** [gvwilson/buildtogether.tech#142]
On https://buildtogether.tech/ the second column of the table of contents seems to be shifted by 1 compared to the first column with chapter titles.

None | Introduction | ---
-- | -- | --
1 | The Important Stuff | Who you are and what you'll learn
2 | Starting | If you read nothing else…
3 | Teams | What to do before you start coding
4 | How to Talk People Into Things | How people can work together productively
5 | Managing Conflict | An essential skill for working with others

**Comment by gvwilson** [comment]
Thanks @czeildi - much appreciated.
